### PR TITLE
Added custom pan responder for the modal backdrop, in order to block swipes on the modal backdrop from being passed along to views behind the backdrop

### PR DESCRIPTION
**Pull request by Elethier**
In my project, we have a modal appearing over a drawer layout. We were surprised to find that pan events (or "swipes") were going through the modal backdrop to the drawer layout while the modal was present. I spent some time experimenting with how to block the pan gestures from reaching the drawer and the best solution I could come with was implementing a custom pan responder for the modal backdrop, so that pan events are silently consumed. (I doubt any users of this library would expect pan gestures to go through the backdrop.) 

While adding the pan responder, I tried to maintain the existing functionality of the backdrop press handler passed in through the modal props. This resulted in having to introduce a "hit slop" property for the backdrop, similar to the `hitSlop` prop on `TouchableWithoutFeedback` within React Native. It's a little clunky, so I'm open to any feedback.

I'm not sure this has been reported as an issue by any other users, but I thought I would submit a fix anyway.

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Thank you for this PR!
I’m in vacation right now but I’ll take a look at it once I’ll be back.

**Comment by mmazzarolo** [comment]
Doesn't this PR break the "swipe to close" functionality of the modal? 🤔

**Comment by Elethier** [comment]
Sorry for the late response @mmazzarolo.

Could you explain the "swipe to close" functionality more? My understanding is that you have to swipe on the _modal_ to close it, not the backdrop. If anyone was trying to close the modal by swiping on the backdrop instead of tapping on the backdrop, then yes, this set of changes would break things.

Although I'm not sure that's a common design pattern for modals...

**Comment by mmazzarolo** [comment]
@Elethier I'm really, really, really sorry I just noticed I didn't answer to your last comment. 😞 
If you (or anyone else) is willing to solve the conflicts and test it again I'm willing to re-open the discussion.

**Comment by mmazzarolo** [comment]
Closing the issue because in the latest versions of the component we went trough a few huge changes on this area. Let me know if you're still having the issue and I'll re-open it! (Sorry again for being so late)

**Pull request closed without merging**
