### PR TITLE
Avoiding null is not an object (r.backdropRef.transitionTo') exception

### PR DESCRIPTION
**Pull request by SudoPlz**
Now checking wether the backdropRef is null before using it

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Great, thanks for the PR @SudoPlz !

**Comment by SudoPlz** [comment]
Awesome.. @mmazzarolo would you be kind enough to use this new version on https://github.com/mmazzarolo/react-native-modal-datetime-picker as well?

A crash caused by `react-native-modal` inside `react-native-modal-datetime-picker` was the reason for this PR.

**Comment by mmazzarolo** [comment]
Done, I released it on `react-native-modal-datetime-picker@5.0.0-0 beta`!

**Comment by SudoPlz** [comment]
You're the boss!! Just make sure you also publish that version to npm so we can use it :)

**Comment by mmazzarolo** [comment]
It's up on npm too, go with `@5.0.0-0`!

**Comment by SudoPlz** [comment]
Awesome 💥

**Pull request merged**
