### PR TITLE
Fixed componentDidUpdate

### PR DESCRIPTION
**Pull request by mmazzarolo**
# Overview

- [x] Fixed the duplicated `componentDidUpdate` introduced in #334 

It's still a WIP because I'm not able to test it now (waiting for the XCode to update and I don't have Android Studio). 
If anyone is willing to test it it would be great (just run `npm i && npm run start:ios` and play a bit with the examples to see if everything is working fine).

### CODE REVIEW

**Comment by mmazzarolo** [comment]
cc @kenyontu @rewieer

**Comment by kenyontu** [comment]
No issues running the example on both Android (6.0) and iOS (12.2)

**Comment by mmazzarolo** [comment]
Thanks @kenyontu !

Waiting for this before publishing: 🙄 
Screenshot 2019-07-31 at 10 38 16

**Comment by richeterre** [comment]
@rewieer @mmazzarolo Any chance you could merge this in soon? Would be nice to have `backdropOpacity` transitions working again! 🙂

**Comment by mmazzarolo** [comment]
@rewieer mind reviewing? thanks sir

**Pull request merged**
