### PR TITLE
Swipe feature

### PR DESCRIPTION
**Pull request by theohdv**
You can now by setting `swipeDirection` swipe the modal in the given direction ('up', 'down', 'right' or 'left').

**New props:**
- `swipeDirection`: When set, enable to swipe the modal in the given direction.
- `onSwipeTreshold`: Treshold for calling onSwipe.
- `onSwipe`: Called when `onSwipeTreshold` has been reach.

**Other changes:**
- Update README (add doc)
- Order prop alphabetically 

**Example:**
```javascript
<Modal
  isVisible={isModalOpen}
  swipeDirection='right'
  onSwipeThreshold={200}
  onSwipe={() => this.setState({ isModalOpen: false })}
>
...
</Modal>

```

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Thank you so much @theohdv, the code seems well written. 

I'll test it this evening/tomorrow 💃

**Comment by mmazzarolo** [comment]
I did some test, you did a great work!
I'm gonna add some comments and tweak it a little and then release it as beta on npm :)

Thank you again 🥇

**Comment by mmazzarolo** [comment]
Released on [v5.0.0-0 pre-release](https://github.com/react-native-community/react-native-modal/releases/tag/v5.0.0-0), thanks!

**Comment by theohdv** [comment]
Glad to hear that! thanks for your reactivity !

**Comment by outdoorra** [comment]
Well done! Already integrated the feature.
Would it be possible to transition from a minimal (bottom) modal to a
bigger more detailed modal? Like Google Maps does it for markers.

**Comment by mmazzarolo** [comment]
@outdoorra at the moment this is not possibile, the swiping feature only handle closing the modal

**Comment by roesneb** [comment]
Well, i guess a workaround would be after the threshold is reached setting the first modal invisible
and a new one could be opened. Not sure though if the animation would go nicely.

**Comment by mmazzarolo** [comment]
@roesneb nope, at least not right now.
It could be implemented for sure in the future, let's just see if the swipe-to-close feature has any bug an then let's talk about future integrations, what do you think?
In the meanwhile you can open a new issue regarding this feature if you're interested! @outdoorra @roesneb

**Comment by roesneb** [comment]
Sounds good to me! Working well so far

**Comment by theOnkar** [comment]
I've implemented the swipe but the modal doesn't hide. The modal drags down to some level and either stays there or comes back to its position.

kdkx3bhzd3



Code:

```
import React, { Component } from 'react';

import {
  StyleSheet, Image, Text, ScrollView, View, TouchableOpacity,
} from 'react-native';

import Modal from "react-native-modal";

class ModalTest extends Component {

  constructor(props) {
    super(props);
    this.state = {
      isModalVisible: false      
    };
  }

    _toggleModal = () =>
    this.setState({ isModalVisible: !this.state.isModalVisible });
  

  render() {

  
    return (
      <ScrollView>

        <View style={{marginTop:20}} />
  
        <View>
        <TouchableOpacity onPress={this._toggleModal}>
          <Text style={styles.showModalText}>Show Modal</Text>
        </TouchableOpacity>
        <Modal 
          isVisible={this.state.isModalVisible}
          // onBackdropPress={() => this.setState({ isVisible: false })}
          swipeDirection="down"
          onSwipeThreshold={100}
          onSwipe={() => this.setState({ isVisible: false })}
          
        >
          <View style={{justifyContent:'center', alignItems:'center'}}>
          <View style={{ padding:10, width:300, height:200, backgroundColor:'#F8F9F9'}}>
            <Text style={{fontSize:24, color: 'red'}}>Hello!</Text>
            <TouchableOpacity onPress={this._toggleModal}>
              <Text style={{color:'black', fontSize:18}}>Hide me!</Text>
            </TouchableOpacity>
          </View>
          </View>
        </Modal>
        </View>


      </ScrollView>

    );
  }
}




export default ModalTest;

```

**Comment by theohdv** [comment]
You have something wrong in your code. You use `this.state.isModalVisible` for the `isVisible` prop but your set `isVisible` in the `onSwipe` method.

Replace your `onSwipe` method with: `onSwipe={() => this.setState({ isModalVisible: false })}`

Then it should work. (Be careful you're having the same mistake in the `onBackdropPress`)

**Comment by theOnkar** [comment]
Thank you so much @theohdv. I missed to check that. Awesome plugin.

**Comment by harshit860** [comment]
@theohdv  Great work Mate

**Pull request merged**
