### PR TITLE
componentWillUnmount is not unsafe

### PR DESCRIPTION
**Pull request by vonovak**
see the list of deprecated methods here https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Oh boy, I don’t even know/remember why it was marked that way. Thanks for the PR!

**Comment by cjerozal** [comment]
Hello. Not sure if you are already aware, but I believe this change fixes a memory leak. Any chance of a release with this fix soon?

More details: I'm looking at using your Modal, but seeing a warning about calling setState/forceUpdate on an unmounted component when I: include your Modal on a screen, navigate there and then to another screen, and then rotate the device. I think it's because: although componentWillUnmount would be called, UNSAFE_componentWillUnmount never is, so without this fix the "didUpdateDimensions" listener is never removed.

**Comment by mmazzarolo** [comment]
Oh, I thought this was released. I’ll release it tomorrow, thank you for reporting it @cjerozal !

**Comment by cjerozal** [comment]
Awesome, thank you for that and all your work on this library!

**Comment by mmazzarolo** [comment]
Available in v7.0.2 :)

**Pull request merged**
