### PR TITLE
fixing previous pull request

### PR DESCRIPTION
**Pull request by G3z**
fixing previous pull request,
sorry

### CODE REVIEW

**Comment by mmazzarolo** [comment]
No worries, I still had to try it :)

**Comment by mmazzarolo** [comment]
Whoops, you closed it just before the merge

**Comment by G3z** [comment]
i noticed something wired with backdrop clicking, sorry again :)

**Comment by G3z** [comment]
i was missing the `pointerEvents="box-none"` and modal was using double margin
should be ok now

**Comment by mmazzarolo** [comment]
Did you try it on both iOS and Android?

**Comment by G3z** [comment]
iOS only, I don't have an android at the moment

**Comment by mmazzarolo** [comment]
Mhhh, the `pointerEvents` prop might be an issue on Android 🤔

**Comment by G3z** [comment]
I copied it from your children wrapping `View`. I don't know if it behaves differently with `KeyboardAvoidingView` on `Android`.
the documentation doesn't specify anything.
You can keep this on hold until someone with android can test it

**Pull request merged**
