### PR TITLE
Fixed broken Android example. 

### PR DESCRIPTION
**Pull request by jkomyno**
The '-' in 'com/react-native-modal-example' caused compilation failure.

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Thank you @jkomyno ! Merged :)

**Comment by JuniusAng** [comment]
@jkomyno did you forget to include change in build.gradle 
`applicationId "com.react-native-modal-example"` to `applicationId "com.example"`?

**Comment by mmazzarolo** [comment]
@JuniusAng thanks for the feedback, I'm on vacation now. Maybe you could send a mini-PR for with this fix if @jkomyno won't answer? 
Thanks! 
I'll merge and check all the remaining issues when I'll be back :)

**Comment by jkomyno** [comment]
Sorry guys, I just noticed. I'll send this PR, np. Thanks @JuniusAng for noticing!

**Pull request merged**
