### PR TITLE
Fix #11

### LINKED ISSUE #11: Tap outside to close
Is there a way to implement that function? Right now when I tap on the darkened region, the modal doesn't close.

### PR DESCRIPTION
**Pull request by tomasreimers**

### CODE REVIEW

**Comment by mmazzarolo** [comment]
@tomasreimers thanks man, I can't test it this week but if you and someone else on #11 can confirm that it works correctly on both Android and iOS and that it doesn't break it's normal behaviour if the backdrop tap to close is disabled I'll merge it now (I'll release it on NPM next week though, I'd like to give it a test too).

**Comment by tomasreimers** [comment]
Already tested. Really would like someone else to test before you merge
though. There's no rush and I've been looking at this so long I'm probably
missing something.

**Comment by benhannel** [comment]
Just used this version as a drop in replacement on my app, and it works great. Tested on Google Pixel Android 7 and iPhone 6 emulator.

**Comment by mmazzarolo** [comment]
Thank you @benhannel, I'll probably test and push it soon 👍

**Comment by mmazzarolo** [comment]
@tomasreimers and @benhannel thank you!
The release notes of `v3.0.0` are [here](https://github.com/react-native-community/react-native-modal/releases/tag/v3.0.0).  
I already submit two other fixes (current release:`v3.0.2`) and we should be stable now, any other test will be super appreciated.

**Pull request merged**
