### PR TITLE
Adding containerWith to props

### PR DESCRIPTION
**Pull request by OctavianRotari**
Adds containerWidth to props, so the user can define the width of the modal. If prop.style has margin set: the code will ignore container width and will use deviceWidth - style.margin * 2

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Hey! Thanks for submitting a PR!
I'm not sure I'm following its goal though, shouldn't the same behaviour be achievable just by using the `style` prop? 🤔

**Comment by OctavianRotari** [comment]
Hey, nevermind my bad got too excited about doing a pull request didn't really think it through :)

**Comment by mmazzarolo** [comment]
@OctavianRotari 😀 no worries! thanks for the effort!

**Comment by OctavianRotari** [comment]
One question though, if you pass the width through with props.style the modal is not centered. I could pass in the margin as part of props.styles but I need to consider the deviceWidth so then the margin will be: (deviceWidth-width)/2 in the styles that I pass down. Will it be useful if this will be done package side?

**Comment by mmazzarolo** [comment]
@OctavianRotari I think it would be better to keep it out of the modal component, mainly to keep the scope down and to make it easier to maintain

**Comment by OctavianRotari** [comment]
@mmazzarolo Say no more, thanks :)

**Pull request closed without merging**
