### PR TITLE
Fix avoidKeyboard feature for Android

### PR DESCRIPTION
**Pull request by Barylskyigb**
This feature was working weirdly for me ([issue](https://github.com/facebook/react-native/issues/11681))

### CODE REVIEW

**Comment by Barylskyigb** [comment]
reopened https://github.com/react-native-community/react-native-modal/pull/86

**Comment by hironarita** [comment]
@mmazzarolo Could you please merge this PR?

**Comment by mmazzarolo** [comment]
@hironarita did you already try it?

**Comment by hironarita** [comment]
@mmazzarolo Yes, it works as expected for me.

**Comment by mmazzarolo** [comment]
Released on [v5.0.0-0 pre-release](https://github.com/react-native-community/react-native-modal/releases/tag/v5.0.0-0), thanks!

**Pull request merged**
