### PR TITLE
Added coverScreen props (@samin) + allow it to be used with a backdrop + typescript

### PR DESCRIPTION
**Pull request by cjroth**
This duplicates https://github.com/react-native-community/react-native-modal/pull/259 and adds the ability to use it with a backdrop as well as adding it to typescript. I've cherry-picked @samin's commits and then resolved conflicts.

I'm guessing that we'd want this to be merged into the "next" branch?

### CODE REVIEW

**Comment by samin** [comment]
@cjroth awesome stuff! Sorry for not replying quickly, been busy. @mmazzarolo Feel free to close my PR https://github.com/react-native-community/react-native-modal/pull/259 and consider this one instead.

**Comment by mmazzarolo** [comment]
(@samin thanks for the feedback!)

**Comment by rewieer** [comment]
Merged, thanks 👍

**Comment by mmazzarolo** [comment]
Available in [v10.0.0-next.0](
https://github.com/react-native-community/react-native-modal/releases/tag/v10.0.0-next.0) ✈️

**Pull request merged**
