### PR TITLE
Added `deviceHeight` and `deviceWidth` props

### PR DESCRIPTION
**Pull request by mmazzarolo**
Added `deviceHeight` and `deviceWidth` props. 
Related discussions:
- #208 
- #147 

Anyone willing to give it a try? (I don't have an S8).

### CODE REVIEW

**Comment by phansw** [comment]
Tried it on my note9. Works only after second render. First render often still leaves the space at the bottom (it seems to not respect deviceHeight on first render). Also, is it intentional to not allow deviceWidth to remain default when just setting deviceHeight?

**Comment by mmazzarolo** [comment]
> Oddly enough, the first modal works (deviceHeight is always respected), but the second modal always disrespects deviceHeight on first render. Subsequent showing of the same second modal will respect the deviceHeight.
🤔 weird, were you able to understand what is causing it?

> Also, is it intentional to not allow deviceWidth to remain default when just setting deviceHeight?

Not really, I just though that if you provide your own custom dimensions you should provide both of them. 

> I tested this on my S8 and it works for making the backdrop smaller, but not for increasing it to fill the screen.
😞 maybe related to [this](https://github.com/facebook/react-native/issues/14887)?

**Comment by mmazzarolo** [comment]
@grit96 AFAIK you can't trust `Dimensions.get("screen")` sizes on S8, that's the reason why I submitted the PR (in fact, if you don't supply your own custom sizes, it uses the ones `Dimensions.get` by default)

**Comment by mmazzarolo** [comment]
@grit96 did you link `react-native-extra-dimensions-android`?

**Comment by phansw** [comment]
I did try with react-native-extra-dimensions and passed it in but the problem still persist - sometimes the modal covers full sometimes not, whether in debug or release build. I even took the height and width and put it into the props as static numbers (copied them from console.log) but the problem still persist. I will try investigating why.

**Comment by phansw** [comment]
I just checked with the inspector. It shows that the modal is indeed set to the correct height. But the blank area at the bottom still appears occasionally. It may be react-native's modal's bug. I'll just wait till I upgrade to React Native 0.57 to see if it resolves this.

**Comment by mmazzarolo** [comment]
😢 let me know if RN 0.57 works correctly (related #216)

**Comment by adcuz** [comment]
Observed on RN 0.57 when not using `react-native-extra-dimensions-android`, so this PR would be very handy as currently I can't see a way to use `react-native-extra-dimensions-android` without these props. Is that right?

**Comment by mmazzarolo** [comment]
> Observed on RN 0.57 when not using react-native-extra-dimensions-android

You mean it's working correctly?

**Pull request merged**
