### PR TITLE
feat: custom backdrop support

### LINKED ISSUE #263: Ability to have custom backdrop?
Hi,

I was wondering whether there are any plans on exposing the backdrop view as a prop to the modal to we can have custom ones. The main idea here would be for blurred backdrops which are quite popular on the iOS platform. At the moment, I can only modify the backdrop styles but blurred backdrop would require changing the underlying `View` to a `BlurView` from `react-native-blur`.

### PR DESCRIPTION
**Pull request by kenyontu**
# Overview
resolves #263 

Adds a prop `customBackdrop` that accepts a React Element and uses it as the backdrop.

Usage example:
```jsx
<Modal
  customBackdrop={<CustomBackdrop />}
>
  Modal content
</Modal>
``` 

Any feedback or changes are welcome 🙂

# Test Plan

I've added a "Custom backdrop" button in the example app, that opens a modal with this new feature.

**Edit 1**: Updated description and usage example to match the new prop type

### CODE REVIEW

**Comment by kenyontu** [comment]
Example using `react-native-blur` to blur the contents bellow the modal:

```jsx
import React, {useState, useRef, useEffect} from 'react';
import {StyleSheet, Text, View, Button, findNodeHandle} from 'react-native';
import Modal from 'react-native-modal';
import {BlurView} from '@react-native-community/blur';

function App() {
  const [isModalVisible, setIsModalVisible] = useState(false);
  const [contentRef, setContentRef] = useState(null);
  const tempRef = useRef(null);

  useEffect(() => {
    setContentRef(findNodeHandle(tempRef.current));
  }, [tempRef.current]);

  const handleOpenModalPress = () => setIsModalVisible(true);
  const handleCloseModalPress = () => setIsModalVisible(false);

  return (
    <View style={styles.container}>
      <View ref={tempRef}>
        <Text style={styles.message}>
          Example text to show the blur effect 🙂
        </Text>
        <Button title="Open modal" onPress={handleOpenModalPress} />
      </View>

      <Modal
        isVisible={isModalVisible}
        backdropOpacity={1} // This is needed, because the default is 0.7
        customBackdrop={props =>
          contentRef ? (
            <BlurView
              {...props}
              viewRef={contentRef}
              blurAmount={10}
              blurRadius={9}
              blurType="light"
            />
          ) : null
        }
      >
        <View style={styles.modalContentContainer}>
          <Text style={styles.modalMessage}>Hello!</Text>
          <Button title="Close modal" onPress={handleCloseModalPress} />
        </View>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#F5FCFF'
  },
  message: {
    fontSize: 16,
    marginTop: 30,
    marginBottom: 10
  },
  modalMessage: {
    marginBottom: 10
  },
  modalContentContainer: {
    backgroundColor: 'white',
    alignItems: 'center',
    padding: 10
  }
});

export default App;
```

**Comment by mmazzarolo** [comment]
@kenyontu thanks for submitting this PR! 
Sorry if I missed something but I have a question: What would be `backdropProps` used for? As far as I understand it is always sending just `flex: 1` in the style, right? In this case it might make more setting it as a component and leave it to the user adding `flex: 1` to the component (and adding it to the docs).

**Comment by rewieer** [comment]
Following what @mmazzarolo said, we can eventually pass an Element instead of a Component. It would cut out an other level of indirection.

**Comment by kenyontu** [comment]
Thanks for the feedback!

@mmazzarolo You are right, it would be much better to pass the component directly. I will add an item in the docs explaining that the backdrop size is up to the user, with an example using `flex: 1`.

@rewieer I will change the prop to receive an Element.

**Comment by mmazzarolo** [comment]
Thanks @kenyontu !

**Pull request merged**
