### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by rekha110254**
Included beforeModalShow method

### CODE REVIEW

**Comment by LouisJS** [comment]
Why for ? Please provide explanation and use case where this could be helpful

**Comment by rekha110254** [comment]
@LouisJS  In my case i'm using beforeModalShow() method to apply custom sound while opening modal.

**Comment by LouisJS** [comment]
IMO, it doesn't belong to the `react-native-modal` repository.
You should do your action the same time you're setting `Modal` to `visible=true`

**Comment by mmazzarolo** [comment]
I agree with @LouisJS , you should do that kind of logic when you show the modal. No need for another trigger :)
Thanks anyway!

**Pull request closed without merging**
