### PR TITLE
Added coverScreen props

### PR DESCRIPTION
**Pull request by samin**
Ability to not render RN Modal component, only what is inside it.

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Hey @samin thanks again for the PR. 
Could you add a bit more context/description to it?  
Is it aiming at using the modal behaviour (animations, swiping, etc...) outside of the scope of the RN Modal (which means it won't cover the entire screen unless it's placed at the root of the app)?  
Thanks!

**Comment by samin** [comment]
Yes @mmazzarolo that's it. I'm building an app that has a toast like notification component that gets triggered every time an action is completed, like for example: `Form saved`, that gets dismissed with a timeout. I've placed this component at the root of the app, and it works great, except it covers the entire screen and does not allow touching anything in the background while the notification is showing. By removing the Modal component, I can still use the animations, dismissal, etc, but it does not cover the entire screen thus a better UX for users. If you have a suggestion on how to achieve this without removing the RN Modal component, I'm all for it too.

**Comment by cjroth** [comment]
Hey @samin looks great, I had a use case for this too - glad you did this!

Don't forget to import `View` from `react-native`, otherwise this will break if merged as is.

Thanks!

**Comment by mmazzarolo** [comment]
P.S.: We (cc @rewieer) are aware of this PR, we're just waiting to release a new react-native-modal version before checking it

**Comment by cjroth** [comment]
I'm using this in my project atm and it's working great with one exception - I found I needed the backdrop even when `coverScreen` is false. I will submit a PR tomorrow for this which will allow the useBackdrop prop to work correctly with coverScreen.

**Comment by mmazzarolo** [comment]
Thanks @cjroth 🙏

**Comment by cjroth** [comment]
Ok, PR here: https://github.com/react-native-community/react-native-modal/pull/271

**Pull request closed without merging**
