### PR TITLE
Use only the name of the animation

### PR DESCRIPTION
**Pull request by yuyao110120**
Multiple 'Modal' custom 'animationIn'/'animationOut' in same view, all animation will be the last 'Modal' animation.

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Hi @yuyao110120 , could you explain it a bit more your PR?  
From my understanding the issue you're solving is that before your PR you couldn't **change** the custom animation once the modal was created because it's name was already set ('animationIn'), so you're basically creating a new name for it by serializing the animation, am I right?

**Comment by yuyao110120** [comment]
@mmazzarolo Yes, your understanding is ok.

**Comment by yuyao110120** [comment]
@mmazzarolo Yes, your understanding is ok.

**Comment by yuyao110120** [comment]
@mmazzarolo I use the serialized way to get a unique animation name that doesn't have coverage problems in multiple Modal coexistence situations.

**Comment by mmazzarolo** [comment]
Merged! 
I'll need to give it a try before publishing it on npm though.  

Thanks :)

**Comment by yuyao110120** [comment]
thx!

**Pull request merged**
