### PR TITLE
Swipe on all directions

### PR DESCRIPTION
**Pull request by rewieer**
Main benefit of this commit is that it relies a lot on existing and doesn't update it by much. Most notable changes : 

* `swipeDirection` can either be a string or an array of strings. Through multiple directions are allowed, only one at a time is supported : that is, if you are dragging to the left, you cannot drag back to the very right unless you release, and drag to the right back again. I think this is logical, but if that's not the desired output I believe this is going to be pretty simple to fix (just change the currentDirection when the delta's sign changes)
* Added a variable to retain the current swipe direction. When `onStartShouldSetPanResponder`is called there's no delta at this point so it has to be taken once a move have been done. 

Tested, doesn't break existing examples. Feedback and more testing welcome !

### CODE REVIEW

**Comment by mmazzarolo** [comment]
🎉 may I ask you to point this pr to the `next` branch?

**Comment by rewieer** [comment]
Done 😃

**Comment by mmazzarolo** [comment]
Thank you! 

> I think this is logical, but if that's not the desired output I believe this is going to be pretty simple to fix (just change the currentDirection when the delta's sign changes)  

I honestly can't give a feedback on this since I don't know what the real use cases for the swiping are 🤔 

Maybe @sunweiyang or @cwcooper who already tested #217 can be helpful here?

Also, just to clarify, this "should" close both #217 and #125 , right?

**Comment by rewieer** [comment]
It should close them both indeed 😄

**Comment by mmazzarolo** [comment]
Merged!

**Comment by mmazzarolo** [comment]
Available in [v10.0.0-next.0](
https://github.com/react-native-community/react-native-modal/releases/tag/v10.0.0-next.0) ✈️

**Pull request merged**
