### PR TITLE
Update react-native to 0.60.5

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates the `react-native` dependency in the example project to `0.60.5` including all project support files.

In a separate commit, it also fixes a few minor ESLint errors.

Successfully verified and tested on:
- Android Device (Xiaomi Mi A2)
- Android Emulator (Pixel 3a)
- iOS Device (iPhone 8)
- iOS Simulator (iPhone X)

### Dependencies in the example project

The example project was cleanly separated into a stand-alone project in the `example` folder, and includes the library code using a relative path (`"file:../"`). With the new React Native version and the updated haste module, a new script `scripts/examples_postinstall.js` is called in the `postinstall` hook of package.json to resolve the haste duplicate dependency problems. This script is based on a file from https://github.com/brodybits/create-react-native-module.

<sub><sup>Once approved, please use a *normal* GitHub merge (i.e. **NO rebase/squash** merge) to integrate the commit(s) from the PR head branch. The changes are broken up into meaningful, [atomic commits](https://www.freshconsulting.com/atomic-commits/), and my branch should already be up-to-date with the latest base branch. If it isn't, or if you want me to change anything, please let me know, and I will update the branch as soon as possible. Thank you!</sup></sub>

### CODE REVIEW

**Comment by mmazzarolo** [comment]
👋 @friederbluemle , thanks for submitting this PR! 
Do you have any other repo example in the community that follows the same pattern you're proposing? (It looks fine for me, just curious).

**Comment by friederbluemle** [comment]
Hi @mmazzarolo - Thanks for the review! :+1: Are you referring to any particular files? I know there's quite a lot of changes, but everything is taken from the default new React Native project (as created by `npx react-native init`).
Btw thanks for merging #339 - The project will now be 100% lint free after merging this PR. ;)
Also rebased with conflicts resolved.

**Comment by mmazzarolo** [comment]
Thanks! Planning to merge it soon.

> Are you referring to any particular files?

I was referring mostly to the `examples_postinstall.js` process.

**Comment by friederbluemle** [comment]
> I was referring mostly to the `examples_postinstall.js` process.

Ooh got it. Sorry for not explaining it in more detail!
I added a section to the PR description. Please let me know if any more clarifications are needed!

**Comment by mmazzarolo** [comment]
(had to squash it because we're following the `semantic-release` commit naming conventions)

**Comment by mmazzarolo** [comment]
@friederbluemle P.S.: We're still looking for active maintainers/helpers for this repo... ping me if you're interested!

**Comment by friederbluemle** [comment]
Thanks @mmazzarolo 👍 
I'd be more than happy to help out with repo maintenance. Let me know how I can help :)

**Pull request merged**
