### PR TITLE
Fix for #11 Tap outside to close

### PR DESCRIPTION
**Pull request by RichardLindhout**

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Hey man, thank you for sending this PR!

I took a close look at it and it seems that the idea of the touchable wrapper + the custom pointerEvents still won't work if you tap on the side of the modal content, am I right?
  
Let me know your point of view on the issue (I'd gladly chat with you on  #11)

**Comment by RichardLindhout** [comment]
If I click on the black in the screenshot it closes. If you click the white nothing happens.
simulator screen shot 29 jul 2017 19 44 28

**Comment by RichardLindhout** [comment]
If you click the white nothing happens. If you click the black it closes.
schermafbeelding 2017-07-29 om 21 24 28

**Comment by mmazzarolo** [comment]
Merged! 
Thank you @RichardLindhout , I'll let you know when it lands on a new NPM release (at the start of next week I think).

**Comment by mmazzarolo** [comment]
@RichardLindhout thank you!
The release notes of `v3.0.0` are [here](https://github.com/react-native-community/react-native-modal/releases/tag/v3.0.0).  
I already submit two other fixes (current release:`v3.0.2`) and we should be stable now, any other test will be super appreciated.

**Comment by RichardLindhout** [comment]
Thank you!

**Pull request merged**
